# General settings
source: "./pattern-library"

# Build settings
markdown: "kramdown"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "astrum-config.json"
  - "package.json"
  - "readme.md"
  - "dist"
  - "assets"